Repository HubSpot/cms-theme-boilerplate, pull requests merged in 2020-12, with the labels that each got.

#283 Fix search field
  src/css/components/_header.css
  src/templates/partials/header.html
Labels: accessibility

#238 Updated pagination to be better for assistive technology users
  src/templates/blog-index.html
  src/templates/blog-post.html
Labels: accessibility, enhancement

#316 Adding JS and styles for subscription preferences template disabled input
  src/css/templates/_system.css
  src/js/main.js
Labels: enhancement
